In [1]:
import pandas as pd
df=pd.read_csv('sentiment.csv',sep='\t',names=['liked','tweet'])
df

      liked                                              tweet
0         1            The Da Vinci Code book is just awesome.
1         1  this was the first clive cussler i've ever rea...
2         1                   i liked the Da Vinci Code a lot.
3         1                   i liked the Da Vinci Code a lot.
4         1  I liked the Da Vinci Code but it ultimatly did...
...     ...                                                ...
6913      0                     Brokeback Mountain was boring.
6914      0       So Brokeback Mountain was really depressing.
6915      0  As I sit here, watching the MTV Movie Awards, ...
6916      0    Ok brokeback mountain is such a horrible movie.
6917      0   Oh, and Brokeback Mountain was a terrible movie.

[6918 rows x 2 columns]

In [2]:
x=df['tweet']
y=df['liked']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english')
x_train=vectorizer.fit_transform(x_train)
x_test=vectorizer.transform(x_test)
x_train

<5534x1594 sparse matrix of type '<class 'numpy.float64'>'
	with 33876 stored elements in Compressed Sparse Row format>

In [4]:
tf_df=pd.DataFrame(x_train.toarray(),columns=vectorizer.get_feature_names())
tf_df

C:\Users\FreeComp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,00,007,10,10pm,12,17,1984,1st,2007,286,...,year,yes,yesterday,yip,young,younger,yuck,yuh,zen,µª
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5531,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5532,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report

In [6]:
lr=LogisticRegression()
print(f'using LogisticRegression: ')
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(f'Training Accuracy :{accuracy_score(y_train,lr.predict(x_train))}')
print(f'Testing Accuracy :{accuracy_score(y_test,y_pred)}')
print(f'Confusion matrix:\n {confusion_matrix(y_test,y_pred)}')
print('-'*33)

using LogisticRegression:
Training Accuracy :0.9978315865558366
Testing Accuracy :0.9934971098265896
Confusion matrix:
 [[578   6]
 [  3 797]]
---------------------------------

In [7]:
x_=vectorizer.transform(['its depressing'])
y_pred_=lr.predict(x_)
y_pred_

array([0], dtype=int64)